services:
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api-gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user
      - mealplan
      - aichat

  user:
    build:
      context: .
      dockerfile: User/Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  mealplan:
    build:
      context: .
      dockerfile: MealPlan/Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  aichat:
    build:
      context: .
      dockerfile: AIChat/Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  stats:
    build:
      context: .
      dockerfile: Stats/Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  health-tracking:
    build:
      context: .
      dockerfile: HealthTracking/Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  recipe:
    build:
      context: .
      dockerfile: Recipe/Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

  notifications:
    build:
      context: .
      dockerfile: Notifications/Dockerfile
    ports:
      - "8087:8087"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-db:27017/menusdb
    depends_on:
      - mongo-db

volumes:
  mongo-data: {}
